

# This file was *autogenerated* from the file ./solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5)#!/usr/bin/sage

v = vector([_sage_const_4 , _sage_const_6 , _sage_const_2 , _sage_const_5 ])
print(v.norm())

