

# This file was *autogenerated* from the file ./solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_846835985 = Integer(846835985); _sage_const_9834798552 = Integer(9834798552); _sage_const_87502093 = Integer(87502093); _sage_const_123094980 = Integer(123094980)#!/usr/bin/sage

def gaussian(v1, v2):
	if (v2.norm() <= v1.norm()):
		temp = v1
		v1 = v2
		v2 = temp

	while (True):
		m = round((v1 * v2) / (v1 * v1))

		if (m == _sage_const_0 ):
			break;
		
		v2 = v2 - m * v1

	return v1, v2

v1 = vector([_sage_const_846835985 , _sage_const_9834798552 ])
v2 = vector([_sage_const_87502093 , _sage_const_123094980 ])

b1, b2 = gaussian(v1, v2)
print(b1 * b2)

